# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  displayName: Download NetCDF
  inputs:
    workingDirectory: $(Build.BinariesDirectory)
    targetType: 'inline'
    script: |
      Invoke-WebRequest $env:URL_NETCDF_WIN -OutFile netcdf.exe
      7z x netcdf.exe bin/*
      Write-Output "##vso[task.prependpath]$env:BUILD_BINARIESDIRECTORY\bin"

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    restoreNugetPackages: true
    
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
