name: build-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  URL_NETCDF_WIN: https://downloads.unidata.ucar.edu/netcdf-c/4.9.2/netCDF4.9.2-NC4-64.exe
jobs:
  build-test-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Download NetCDF
      shell: pwsh
      run: |
        Invoke-WebRequest $env:URL_NETCDF_WIN -OutFile ${{ runner.temp }}\netcdf.exe
        7z x ${{ runner.temp }}\netcdf.exe bin/* -o${{ runner.temp }} -y
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        LIBNETCDFPATH: ${{ runner.temp }}\bin\netcdf.dll

  build-test-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore ScientificDataSet
    - name: Download NetCDF
      run: sudo apt-get install libnetcdf-dev
    - name: Test
      run: dotnet test --verbosity normal SDSLiteTests

  build-test-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore ScientificDataSet
    - name: Download NetCDF
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1
      run: brew install netcdf
    - name: Test
      run: dotnet test --verbosity normal SDSLiteTests
