name: build-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  URL_NETCDF_WIN: http://www.unidata.ucar.edu/downloads/netcdf/ftp/netCDF4.7.2-NC4-64.exe
jobs:
  build-test-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Download NetCDF
      shell: pwsh
      run: |
        Invoke-WebRequest $env:URL_NETCDF_WIN -OutFile netcdf.exe
        7z x netcdf.exe bin/*
        Add-Content -Path $env:GITHUB_PATH -Value (Join-Path (Get-Location) "bin")  -Encoding UTF8
    - name: Test
      run: dotnet test --no-build --verbosity normal

  build-test-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore ScientificDataSet
    - name: Download NetCDF
      run: sudo apt-get install libnetcdf-dev
    - name: Test
      run: dotnet test --verbosity normal SDSLiteTests

  build-test-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore ScientificDataSet
    - name: Download NetCDF
      run: brew install netcdf
    - name: Test
      run: dotnet test --verbosity normal SDSLiteTests
